version: 2.1

# orbs for necessary dependencies
orbs:
  node: circleci/node@5.0.1
  aws-cli: circleci/aws-cli@1.3.1
  eb: circleci/aws-elastic-beanstalk@2.0.1

jobs:
  build:
    docker: #docker is a virtual space used for operating the pipeline
      - image: "cimg/base:stable"
    steps: #these steps are preformed on the virtual space for prepration
      - node/install
      - checkout
      - aws-cli/setup
      - eb/setup
      - run: #start running the deployment process
          name: Front-End Install
          command: |
            npm run frontend:install
      - run:
          name: Back-End Install
          command: |
            npm run backend:install
      - run:
          name: Front-End Build
          command: |
            npm run frontend:build
      - run:
          name: Back-End Build
          command: |
            npm run backend:build
      - run:
          name: Deploy App
          command: |
            npm run deploy
